name: CI

on: push

jobs:
  build:
    name: Surge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Deploy
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'roberto-snake-game.surge.sh'
          project: '.'
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}
